#!/bin/bash
old_fullpath=$PV_APP_ROOT/$OLD_FILEPATH
new_fullpath=$PV_APP_ROOT/$NEW_FILEPATH
new_dirname=`dirname $new_fullpath`
if [ ! -d $new_dirname ]; then
    /bin/mkdir -p $new_dirname
fi

/bin/mv "$old_fullpath" "$new_fullpath"

old_dirname=`dirname $old_fullpath`
if [ -z "$(/bin/ls -A $old_dirname)" ]; then
    /bin/rm -d $old_dirname
fi
