#!/bin/bash
pushd $PV_APP_ROOT >/dev/null
/usr/bin/find $PV_APP_ROOT -path $PV_APP_ROOT/.pv -prune -o \
                           -path $PV_APP_ROOT/.git -prune -o \
                           -path $PV_APP_ROOT/node_modules -prune -o \
                           -path $PV_APP_ROOT/.config -prune -o \
                           -path $PV_APP_ROOT/.npmrc -prune -o \
                           -type f -printf '%P\n' | \
/bin/tar -c -T -
popd >/dev/null
